---

- name: 1.) Launching EC2 Instance for Nginx and Load Balancing
  ec2:
     key_name: "{{ AWS_KEY_PAIR }}"
     instance_type: t2.small
     image: ami-0123b531fc646552f
     group: ['whitelist1', 'whitelist2']
     aws_access_key: "{{ ACCESS_KEY }}"
     aws_secret_key: "{{ SECRET_KEY }}"
     region: ap-south-1
     wait: yes
     wait_timeout: 500
     count: 1
     instance_profile_name:
        CodeDeploy-EC2-Instance-Profile
     instance_tags:
        Name: Ansible - Nginx Server
     vpc_subnet_id: "{{ SUBNET }}"
     assign_public_ip: yes
  register: ec2

- name: 2.) Printing the private IP
  debug:
    msg: "{{ item.private_ip }}"
  with_items: "{{ ec2.instances }}"


